name: CI

on:
    push:
        branches:
            - '**'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Start all containers
              working-directory: docker
              run: docker compose up -d --build

            - name: Run PHPUnit tests
              run: docker compose exec -T php-fpm vendor/bin/phpunit

            - name: Run PHPCS (PSR-12)
              run: docker compose exec -T php-fpm vendor/bin/phpcs -n -s -p --standard=PSR12 src/

            - name: Run PHPStan (level 2)
              run: docker compose exec -T php-fpm vendor/bin/phpstan analyse -l 2 --memory-limit=512M --error-format=raw src/
